# Generated by Django 2.0.3 on 2018-04-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='service_contact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='date_installed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='lead_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='supplier',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
