# Generated by Django 2.0.3 on 2018-04-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_part_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='date_installed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
