# Generated by Django 2.0.3 on 2018-04-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20180416_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='lead_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
