# Generated by Django 2.0.3 on 2018-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20180422_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='equipment_files'),
        ),
    ]
