# Generated by Django 2.0.3 on 2018-04-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='files',
        ),
    ]
