# Generated by Django 2.0.3 on 2018-04-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_remove_equipment_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='equipment_files'),
        ),
    ]
