# Generated by Django 2.0.3 on 2018-04-22 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0005_auto_20180422_1317'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=200, verbose_name='Summary of work done/issue')),
                ('description', models.TextField(help_text='Please be as descriptive as possible and include all details.')),
                ('issue_datetime', models.DateTimeField(blank=True, help_text='Date and time of estimated start of issue or maintenance work', null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_datetime', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
    ]
