# Generated by Django 2.0.3 on 2018-04-22 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20180422_1317'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='150 character limit description of maintenance service', max_length=150)),
                ('frequency', models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Semi-annually'), (6, 'Annually'), (7, '2 Years'), (8, '4 Years')], verbose_name='Service Frequency')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Person who worked on the Machine', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='resolved_datetime',
            field=models.DateTimeField(blank=True, help_text='Time machine was ready for production', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='services',
            field=models.ManyToManyField(help_text='Pre-scheduled services completed with this log', to='logs.Service'),
        ),
    ]
