# Generated by Django 2.0.3 on 2018-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20180422_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Pre-scheduled services completed with this log', to='logs.Service'),
        ),
    ]
