# Generated by Django 2.0.3 on 2018-04-24 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0006_auto_20180422_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Person responsible for log activity.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Person closing the log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
