# Generated by Django 2.0.3 on 2018-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_service_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='files',
            field=models.FileField(blank=True, help_text='Any files or images associated with this log.', null=True, upload_to='log_files/'),
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional details regarding the maintenance service.'),
        ),
    ]
