# Generated by Django 2.0.3 on 2018-04-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_auto_20180430_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='files',
        ),
    ]
