# Generated by Django 2.0.3 on 2018-04-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_remove_log_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='file',
            field=models.FileField(blank=True, help_text='Any file or image associated with this log.', null=True, upload_to='log_files/'),
        ),
    ]
